name: From Noob to Legends - Roadmaps

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linux:
    name: Starter with linux
    runs-on: ubuntu-latest

    steps:
      - name: Welcome to Ubuntu
        run: echo Hello Ubuntu!

      - name: What is Linux, struct of linux
        run: |
          echo L0 - Kernel managing hardware resource, files, processing, network and security
          echo L1 - Shell forward command to Kernel. Ubuntu and Centos using bash shell
          echo L2 - Application is friendly for user managing shell
          echo L2 - Install Application by apt on ubuntu from repo
          echo sudo apt update - update package list database
          echo sudo apt upgrade - upgrade newest version package on machine
      - name: Linux directory structure
        run: |
          echo / : root directory
          echo /bin : Directory contain binary for system or application
          echo /boot : Directory contain binary for boot
          echo /dev : Directory contain for hardward
          echo /etc : config file for system and application
          echo /home : List User folder
          echo /lib or lib64 : Library  file
          echo /opt : option - extension or application 3rd
          echo /tmp : temporary file - Clear on reboot
          echo /usr : User shared file and program
          echo /var : logfiles
      - name: Root and user command
        run: |
          echo sudo + command : use command as root
          echo sudo passwd root  : change password root
          echo cd : go to folder and file
          echo cd / : go to top directory
          cd /
          ls -al
          echo -------------------------------------------------------
          echo cd .. : go up one level directory
          cd /home
          ls -al
          echo -------------------------------------------------------
          echo "cd ~ : go to current user home directory (example : root user is /root, user sample is /home/sample)"
          cd ~
          echo Can use : cd ~user for go to specific user
          echo -------------------------------------------------------
          echo pwd : print working directory
          cd /home
          pwd
      - name: Working with file and Direction
        run: |
          echo ls : List files and folders
          echo -a : all file, include hidden
          echo -l : list all attribute, size, date, permission...
          echo -R : list sub direction
          echo -t : sort by last modify time
          echo -r : reverse order
          echo example : ls -lat
          cd ~
          ls -lat
          echo -------------------------------------------------------
          echo mkdir : Create directory
          echo -p : quick create sub direction
          echo example : mkdir -p dir/dir_sub/dir_sub_sub
          mkdir -p test/dir/dir_sub/dir_sub_sub
          cd test
          ls -R
          echo example quick create multiple
          mkdir dir1 dir2 dir3
          ls -R
          echo -------------------------------------------------------
          echo du : disk usage - view size of directory and files
          echo -------------------------------------------------------
          echo rmdir : remove empty directory - use -p for delete sub folder also
          echo example rmdir -p dir/dir_sub/dir_sub_sub
          ls -R
          rmdir -p dir/dir_sub/dir_sub_sub
          ls -R
          echo -------------------------------------------------------
          echo cp : copy file and directory
          echo  -v : view wtf running after command
          echo -i : need confirm
          echo -R : directory and sub
          echo example view list here
          sudo apt install tree
          mkdir dir1/sub_dir1  dir1/sub_dir2
          tree
          cp -r dir1/sub_dir1 dir2
          ls -R
          echo -------------------------------------------------------
          echo mv : move file and directory
          echo example : mv dir2/sub_dir1 dir3
          ls -R
          mv dir2/sub_dir1 dir3
          ls -R
